CREATE DATABASE IF NOT EXISTS nsp_db;

USE nsp_db;

CREATE TABLE IF NOT EXISTS user_data (
    user_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(20) NOT NULL,
    `name`  VARCHAR(50) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    email_id VARCHAR(100) NOT NULL,
    reg_date DATE DEFAULT (CURRENT_DATE) NOT NULL
);

CREATE TABLE IF NOT EXISTS note_data (
    note_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    upload_date DATE DEFAULT (CURRENT_DATE) NOT NULL,
    upload_time TIME DEFAULT (CURRENT_TIME) NOT NULL,
    view_link TEXT NOT NULL,
    download_link TEXT NOT NULL
);
